{{ if .Values.ingress.active }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-rules {{ if .Values.ingress.annotations }}
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }} {{ end }}
spec: {{ if .Values.ingress.tls_secret_name }}
  tls:
  - hosts:
    - {{ .Values.host_name }}
    secretName: {{ .Values.ingress.tls_secret_name }} {{ end }}
  rules:
  - host: {{ .Values.host_name }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: tesk-api
          servicePort: {{ .Values.tesk.port }}
{{ end }}
